add support for revolt energy monitor nc-5462
merbanan/rtl_433 pull request #2361
Opened 2023-02-03 22:29 UTC by nicolaihess

Power Plug Energy Monitor NC-5642 (from www.revolt-power.de).

2023-02-03 22:48 UTC, zuckschwerdt requested changes
Thanks, this looks good, some style changes though :)

2023-02-03 22:48 UTC, zuckschwerdt commented on README.md
> +    [233]* CED7000 Shot Timer
Can you rebase and `./maintainer_update.py` so this change does not appear?

2023-02-03 22:48 UTC, zuckschwerdt commented on README.md
> +	SoapySDR device driver is not available.
This change must be excluded from the PR

2023-02-03 22:48 UTC, zuckschwerdt commented on man/man1/rtl_433.1
> +SoapySDR device driver is not available.
This change must be excluded from the PR.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +    Revolt NC5462 Energy Monitor
Add a dot at the end.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +  revolt energy power meter.
Please remove the leading 2 spaces in *this* section.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +  Pulses
Review the formatting, this is markdown. Newlines don't actually break. Use list with dashes (`-`) for e.g. the items below.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +#include "r_util.h"
Do you really need r_util.h? You should not.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +static int check_bitbuffer_row1byte12(bitbuffer_t *bitbuffer) {
This should be placed into the decoder and not be a function.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +/**
There must not be a (doc-)comment here! There is already above.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +static int revolt_nc5462_callback(r_device *decoder, bitbuffer_t *bitbuffer)
Name it `revolt_nc5462_decode`.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +    bitrow_t *bb = bitbuffer->bb;
If you work with only row 0 then it should be `uint8_t *b = bitbuffer->bb[0]` not `bb`.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +      id = (bb[0][0]<<8) | (bb[0][1]);
All indents are 4 spaces per level please.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +      data = data_make(
Wrap in `    /* clang-format off */` and `    /* clang-format on */` please. Format as table, see other decoders.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +    return 0;
This return should be an early abort right at the top, not a nested block please.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +        "time",
remove `time`

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +                "current", "Current ",DATA_FORMAT, "%.02f A ",  DATA_DOUBLE, .01 * current,
usually we write `current * 0.01,`

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +                "power", "Power",  DATA_FORMAT, "%.02f W",DATA_DOUBLE, .1*power,
all these keys should have units, e.g. `voltage_V`, `current_A`, `frequency_Hz`, `power_W`, `energy_kWh`.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +                "power factor", "power factor",DATA_FORMAT, "%.02f Pf",  DATA_DOUBLE, .01*pf,
no spaces in keys please, also below.

2023-02-03 22:48 UTC, zuckschwerdt commented on src/devices/revolt_nc5462.c
> +r_device revolt_nc5462 = {
Needs to be `r_device const revolt_nc5462 = {` -- since yesterday now ;)

2023-02-03 23:27 UTC, merbanan commented on src/devices/revolt_nc5462.c
> +                "detect flag", "Detect Flag", DATA_STRING, detect_flag ? "Yes" : "No",
Integrity tag is missing.

2023-02-03 23:28 UTC, merbanan commented on src/devices/revolt_nc5462.c
> +    if (check_bitbuffer_row1byte12(bitbuffer)) {
The checksum check should return the proper type. Look at other decoders for inspiration.

2023-02-03 23:29 UTC, merbanan commented
And send some signal samples if that has not been sent.

2023-02-04 20:55 UTC, nicolaihess commented
Thanks for the review and feedback. I will try to apply the changes.
And I am about to add signal samples and device descriptions on rtl_433_tests
(Should have read the contribution page first :) )

2023-02-15 21:29 UTC, zuckschwerdt approved these changes

2023-02-16 21:54 UTC, merged

2023-02-16 22:15 UTC, zuckschwerdt commented
Merge with some changes on top. Only noticeable changes are:
- "model" is now "Revolt-NC5462"
- "detect_mode" renamed to "button" with 0/1 output like in other decoders.

2023-02-25 22:31 UTC, nicolaihess commented
thanks for finishing and taken the pull request.